---
apiVersion: v1
kind: Namespace
metadata:
  name: snack101
  labels:
    name: snack101
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: snack101-config
  namespace: snack101
data:
  DATABASE_URL: "sqlite:///./snack101.db"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snack101-app
  namespace: snack101
  labels:
    app: snack101
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snack101
  template:
    metadata:
      labels:
        app: snack101
    spec:
      containers:
      - name: snack101
        image: snack101:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: snack101-config
              key: DATABASE_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: snack101-service
  namespace: snack101
  labels:
    app: snack101
spec:
  selector:
    app: snack101
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snack101-ingress
  namespace: snack101
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: snack101.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: snack101-service
            port:
              number: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: snack101-hpa
  namespace: snack101
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: snack101-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
