apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml

commonLabels:
  app.kubernetes.io/name: snack101
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: argocd