apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: snack101
type: Opaque
data:
  # MySQL root 비밀번호 (base64 인코딩된 "snack101password")
  mysql-root-password: c25hY2sxMDFwYXNzd29yZA==
  # MySQL 사용자 비밀번호 (base64 인코딩된 "snack101user")
  mysql-password: c25hY2sxMDF1c2Vy
