apiVersion: apps/v1
kind: Deployment
metadata:
  name: snack101-app
  namespace: snack101-staging
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: snack101
        image: snack101:develop
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
