apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: snack101-staging

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml
- hpa-patch.yaml

commonLabels:
  environment: staging
